name: async_redux
description: A Redux version which is easy to learn, to use, to test, and has no boilerplate. Allows for both sync and async reducers. Tailored for Flutter.
version: 2.8.2
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/async_redux

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  logging: ^0.11.3+2
  path: ^1.6.4
  path_provider: ^1.4.4
  file: ^5.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.3
  async: ^2.4.1
  flutter_test:
    sdk: flutter

flutter:

